exports.seed = function (knex, Promise) {
  return knex('movies').del()
    .then(function () {
      return knex('users').insert([
        {id: 1, movie: 'A.I.', year: 2001, director: Steven Spielberg}, 
        {id: 2, movie: After Earth, year: 2013, director: M. Night Shyamalan,}, 
        {id: 3, movie: Alien, year: 1979, director: Ridley Scott}, 
        {id: 4, movie: Alien vs Predator, year: 2004, director: Paul W. S. Anderson}, 
        {id: 5, movie: Avatar, year: 2009, director: James Cameron},
        {id: 6, movie: Back To The Future, year: 1985, director: Robert Zemeckis,}, 
        {id: 7, movie: Battlefield Earth, year: 2000, director: Roger Christian,}, 
        {id: 8, movie: Blade Runner, year: 1982, director: Ridley Scott,}, 
        {id: 9, movie: Click, year: 2006, director: Frank Coraci,}, 
        {id: 10, movie: Cowboys Vs Aliens, year: 2011, director: Jon Favreau,},
        {id: 11, movie: District 9, year: 2009, director: Neill Blomkamp,}, 
        {id: 12, movie: Jurassic Park, year: 1993, director: Steven Spielberg,}, 
        {id: 13, movie: E. T., year: 1982, director: Steven Spielberg,},
        {id: 14, movie: Edge Of Tomorrow, year: 2014, director: Doug Liman,}, 
        {id: 15, movie: Ex Machina, year: 2014, director: Alex Garland,}, 
        {id: 16, movie: Geostorm, year: 2017, director: Dean Delvin,}, 
        {id: 17, movie: Gravity, year: 2013, director: Alfonso,}, 
        {id: 18, movie: Inception, year: 2010, director: Christopher Nolan,}, 
        {id: 19, movie: Independance Day, year: 1996, director: Roland Emmerich,},
        {id: 20, movie: Interstellar, year: 2014, director: Christopher Nolan,},
        {id: 21, movie: Looper, year: 2012, director: Rian Johnson,},
        {id: 22, movie: Mars Attacks, year: 1996, director: Tim Burton,},
        {id: 23, movie: Minority Report, year: 2002, director: Steven Spielberg,},
        {id: 24, movie: Pacific Rim, year: 2013, director: Guillermo Del Toro,},
        {id: 25, movie: Pixels, year: 2015, director: Chris Columbus,}, 
        {id: 26, movie: Prometheus, year: 2012, director: Ridley Scott,},  
        {id: 27, movie: Robocop, year: 1987, director: Paul Verhoeven,},  
        {id: 28, movie: Source Code, year: 2011, director: Duncan Jones,},  
        {id: 29, movie: Space Odessy 2001, year: 2001, director: Stanley Kubrick,},  
        {id: 30, movie: Star Trek, year: 2009, director: J. J. Abrams,},  
        {id: 31, movie: Star Wars - A New Hope, year: 1977, director: George Lucas,},  
        {id: 32, movie: Starship Troopers, year: 1997, director: Paul Verhoeven,},  
        {id: 33, movie: Terminator, year: 1984, director: James Cameron,}, 
        {id: 34, movie: The Avengers, year: 2012, director: Joss Whedon,},   
        {id: 35, movie: The Fifth Element, year: 1997, director: Luc Besson,},   
        {id: 36, movie: The Martian, year: 2015, director: Ridley Scott,},   
        {id: 37, movie: The Matrix, year: 1999, director: Lana Wachowski,},   
        {id: 38, movie: The Thing, year: 1982, director: John Carpenter,},  
        {id: 39, movie: Total Recall, year: 1990, director: Paul Verhoeven,},  
        {id: 40, movie: Transformers, year: 2007, director: Michael Bay,},  
        {id: 41, movie: Tron Legacy, year: 2010, director: Joseph Kosinski,},  
        {id: 42, movie: Waterworld, year: 1997, director: Kevin Reynolds,}, 
       ])
    })
}
